title: Cesare Maio
description: Cesare Maio's personal GitHub Pages site
# theme: jekyll-theme-cayman
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
google_analytics: 
show_downloads: false
